In [10]:
import pandas as pd
import numpy as np
%matplotlib inline

In [11]:
datosair = pd.read_csv("historicoaire15.csv",sep=",")
datosair = datosair.drop(datosair.columns[0],axis=1)
datosair.head()

   anio  mes  dia    SO2    CO      NO2      PM2.5  PM10    BEN   O3
0    15    1    1  14.25  0.98  100.000  28.666667  38.2  2.025  8.0
1    15    1    2  14.00  0.94  109.500  21.000000  29.6  1.975  4.2
2    15    1    3  11.75  0.82   94.625  19.000000  25.2  1.800  4.4
3    15    1    4  13.00  0.88   98.500  18.000000  24.0  1.875  6.2
4    15    1    5  11.50  0.76   89.875  18.333333  25.4  1.700  6.4

In [12]:
calidad15pm10 = []
aux15pm10 = []
calidad15so2 = []
aux15so2 = []
calidad15no2 = []
aux15no2 = []
calidad15co = []
aux15co = []
calidad15o3 = []
aux15o3 = []
for i in range(len(datosair)):
    if (datosair.ix[i,'PM10']<=50):
        calidad15pm10.append('buena')
        aux15pm10.append(0)
    if (datosair.ix[i,'SO2']<=175):
        calidad15so2.append('buena')
        aux15so2.append(0)
    if (datosair.ix[i,'NO2']<=100):
        calidad15no2.append('buena')
        aux15no2.append(0)
    if (datosair.ix[i,'CO']<=5):
        calidad15co.append('buena')
        aux15co.append(0)
    if (datosair.ix[i,'O3']<=90):
        calidad15o3.append('buena')
        aux15o3.append(0)
    if (50<datosair.ix[i,'PM10']<=90):
        calidad15pm10.append('admisible')
        aux15pm10.append(1)
    if (175<datosair.ix[i,'SO2']<=350):
        calidad15so2.append('admisible')
        aux15so2.append(1)
    if (100<datosair.ix[i,'NO2']<=200):
        calidad15no2.append('admisible')
        aux15no2.append(1)
    if (5<datosair.ix[i,'CO']<=10):
        calidad15co.append('admisible')
        aux15co.append(1)
    if (90<datosair.ix[i,'O3']<=180):
        calidad15o3.append('admisible')
        aux15o3.append(1)
    if (90<datosair.ix[i,'PM10']<=150):
        calidad15pm10.append('deficiente')
        aux15pm10.append(2)
    if (350<datosair.ix[i,'SO2']<=525):
        calidad15so2.append('deficiente')
        aux15so2.append(2)
    if (200<datosair.ix[i,'NO2']<=300):
        calidad15no2.append('deficiente')
        aux15no2.append(2)
    if (10<datosair.ix[i,'CO']<=15):
        calidad15co.append('deficiente')
        aux15co.append(2)
    if (180<datosair.ix[i,'O3']<=240):
        calidad15o3.append('deficiente')
        aux15o3.append(2)
    if (150<datosair.ix[i,'PM10']):
        calidad15pm10.append('mala')
        aux15pm10.append(3)
    if (525<datosair.ix[i,'SO2']):
        calidad15so2.append('mala')
        aux15so2.append(3)
    if (300<datosair.ix[i,'NO2']):
        calidad15no2.append('mala')
        aux15no2.append(3)
    if (15<datosair.ix[i,'CO']):
        calidad15co.append('mala')
        aux15co.append(3)
    if (240<datosair.ix[i,'O3']):
        calidad15o3.append('mala')
        aux15o3.append(3)

In [13]:
calidad15 = []
for i in range(len(datosair)):
    aux15 = []
    aux15.append(aux15pm10[i])
    aux15.append(aux15so2[i])
    aux15.append(aux15no2[i])
    aux15.append(aux15co[i])
    aux15.append(aux15o3[i])
    maximo = max(aux15)
    if maximo == 0:
        calidad15.append('buena')
    elif maximo == 1:
        calidad15.append('admisible')
    elif maximo == 2:
        calidad15.append('deficiente')
    elif maximo == 3:
        calidad15.append('mala')
    else:
        calidad15.append('no')

In [14]:
datosair['calidadpm10'] = calidad15pm10 
datosair['calidadso2'] = calidad15so2 
datosair['calidadno2'] = calidad15no2
datosair['calidadco'] = calidad15co
datosair['calidado3'] = calidad15o3
datosair['calidad'] = calidad15

In [15]:
datostiempo = pd.read_csv("historicotiempo15.csv",sep=",")
datostiempo = datostiempo.drop(datostiempo.columns[0],axis=1)
datostiempo.head()

   anio  mes  dia temperatura tempmax tempmin prob_precipitacion viento
0    15    1    1         1.4    13.1      -6                  0    4.1
1    15    1    2         1.9    13.8      -6                  0    4.4
2    15    1    3         2.8    14.2      -4                  0    3.5
3    15    1    4         4.4      18      -3                  0    3.1
4    15    1    5         4.1    14.1      -2                  0    3.5

In [16]:
datostrafic = pd.read_csv("historicotrafico15.csv",sep=",")
datostrafic = datostrafic.drop(datostrafic.columns[0],axis=1)
datostrafic.head()

   anio  mes  dia   intensidad       vmed
0    15    1    1   923.583873  69.025097
1    15    1    2  1250.291586  66.092644
2    15    1    3  1032.828901  69.092690
3    15    1    4   952.586972  69.246389
4    15    1    5  1315.380665  67.709120

In [17]:
df = datosair.copy(deep=True)
df['temperatura']=datostiempo['temperatura']
df['tempmax']=datostiempo['tempmax']
df['tempmin']=datostiempo['tempmin']
df['prob_precipitacion']=datostiempo['prob_precipitacion']
df['viento']=datostiempo['viento']
df['intensidad']=datostrafic['intensidad']
df['vmed']=datostrafic['vmed']
df.head()

,anio,mes,dia,SO2,CO,NO2,PM2.5,PM10,BEN,O3,...,calidadco,calidado3,calidad,temperatura,tempmax,tempmin,prob_precipitacion,viento,intensidad,vmed
0,15,1,1,14.25,0.98,100.000,28.666667,38.2,2.025,8.0,...,buena,buena,buena,1.4,13.1,-6,0,4.1,923.583873,69.025097
1,15,1,2,14.00,0.94,109.500,21.000000,29.6,1.975,4.2,...,buena,buena,admisible,1.9,13.8,-6,0,4.4,1250.291586,66.092644
2,15,1,3,11.75,0.82,94.625,19.000000,25.2,1.800,4.4,...,buena,buena,buena,2.8,14.2,-4,0,3.5,1032.828901,69.092690
3,15,1,4,13.00,0.88,98.500,18.000000,24.0,1.875,6.2,...,buena,buena,buena,4.4,18,-3,0,3.1,952.586972,69.246389
4,15,1,5,11.50,0.76,89.875,18.333333,25.4,1.700,6.4,...,buena,buena,buena,4.1,14.1,-2,0,3.5,1315.380665,67.709120

In [18]:
df.to_csv("year2015respuesta.csv",index=False)