In [10]:
import pandas as pd
import numpy as np
%matplotlib inline

In [11]:
datosair = pd.read_csv("historicoaire16.csv",sep=",")
datosair = datosair.drop(datosair.columns[0],axis=1)
datosair.head()

   anio  mes  dia   SO2    CO     NO2      PM2.5  PM10    BEN    O3
0    16    1    1  7.50  0.30  35.125  13.000000  15.6  0.750  23.8
1    16    1    2  7.25  0.28  27.375   5.000000  10.0  0.575  43.0
2    16    1    3  6.75  0.28  27.750   5.000000   8.8  0.625  33.2
3    16    1    4  6.75  0.22  19.750   3.333333   4.4  0.300  35.6
4    16    1    5  6.75  0.28  27.125   3.000000   4.8  0.500  56.2

In [12]:
calidad16pm10 = []
aux16pm10 = []
calidad16so2 = []
aux16so2 = []
calidad16no2 = []
aux16no2 = []
calidad16co = []
aux16co = []
calidad16o3 = []
aux16o3 = []
for i in range(len(datosair)):
    if (datosair.ix[i,'PM10']<=50):
        calidad16pm10.append('buena')
        aux16pm10.append(0)
    if (datosair.ix[i,'SO2']<=175):
        calidad16so2.append('buena')
        aux16so2.append(0)
    if (datosair.ix[i,'NO2']<=100):
        calidad16no2.append('buena')
        aux16no2.append(0)
    if (datosair.ix[i,'CO']<=5):
        calidad16co.append('buena')
        aux16co.append(0)
    if (datosair.ix[i,'O3']<=90):
        calidad16o3.append('buena')
        aux16o3.append(0)
    if (50<datosair.ix[i,'PM10']<=90):
        calidad16pm10.append('admisible')
        aux16pm10.append(1)
    if (175<datosair.ix[i,'SO2']<=350):
        calidad16so2.append('admisible')
        aux16so2.append(1)
    if (100<datosair.ix[i,'NO2']<=200):
        calidad16no2.append('admisible')
        aux16no2.append(1)
    if (5<datosair.ix[i,'CO']<=10):
        calidad16co.append('admisible')
        aux16co.append(1)
    if (90<datosair.ix[i,'O3']<=180):
        calidad16o3.append('admisible')
        aux16o3.append(1)
    if (90<datosair.ix[i,'PM10']<=150):
        calidad16pm10.append('deficiente')
        aux16pm10.append(2)
    if (350<datosair.ix[i,'SO2']<=525):
        calidad16so2.append('deficiente')
        aux16so2.append(2)
    if (200<datosair.ix[i,'NO2']<=300):
        calidad16no2.append('deficiente')
        aux16no2.append(2)
    if (10<datosair.ix[i,'CO']<=15):
        calidad16co.append('deficiente')
        aux16co.append(2)
    if (180<datosair.ix[i,'O3']<=240):
        calidad16o3.append('deficiente')
        aux16o3.append(2)
    if (150<datosair.ix[i,'PM10']):
        calidad16pm10.append('mala')
        aux16pm10.append(3)
    if (525<datosair.ix[i,'SO2']):
        calidad16so2.append('mala')
        aux16so2.append(3)
    if (300<datosair.ix[i,'NO2']):
        calidad16no2.append('mala')
        aux16no2.append(3)
    if (15<datosair.ix[i,'CO']):
        calidad16co.append('mala')
        aux16co.append(3)
    if (240<datosair.ix[i,'O3']):
        calidad16o3.append('mala')
        aux16o3.append(3)

In [13]:
calidad16 = []
for i in range(len(datosair)):
    aux16 = []
    aux16.append(aux16pm10[i])
    aux16.append(aux16so2[i])
    aux16.append(aux16no2[i])
    aux16.append(aux16co[i])
    aux16.append(aux16o3[i])
    maximo = max(aux16)
    if maximo == 0:
        calidad16.append('buena')
    elif maximo == 1:
        calidad16.append('admisible')
    elif maximo == 2:
        calidad16.append('deficiente')
    elif maximo == 3:
        calidad16.append('mala')
    else:
        calidad16.append('no')

In [14]:
datosair['calidadpm10'] = calidad16pm10 
datosair['calidadso2'] = calidad16so2 
datosair['calidadno2'] = calidad16no2
datosair['calidadco'] = calidad16co
datosair['calidado3'] = calidad16o3
datosair['calidad'] = calidad16

In [15]:
datostiempo = pd.read_csv("historicotiempo16.csv",sep=",")
datostiempo = datostiempo.drop(datostiempo.columns[0],axis=1)
datostiempo.head()

   anio  mes  dia  temperatura  tempmax  tempmin  prob_precipitacion  viento
0    16    1    1         10.9       14      7.6                0.00     8.0
1    16    1    2          8.4       12      5.0                3.81    16.5
2    16    1    3          7.4       10      4.0                0.00    19.3
3    16    1    4         12.1       13      8.0                0.51    38.7
4    16    1    5          6.9        9      5.0                4.32    23.5

In [16]:
datostrafic = pd.read_csv("historicotrafico16.csv",sep=",")
datostrafic = datostrafic.drop(datostrafic.columns[0],axis=1)
datostrafic.head()

   anio  mes  dia  intensidad       vmed
0    16    1    1  890.573791  68.675248
1    16    1    2   -1.000000  -1.000000
2    16    1    3   -1.000000  -1.000000
3    16    1    4   -1.000000  -1.000000
4    16    1    5   -1.000000  -1.000000

In [17]:
df = datosair.copy(deep=True)
df['temperatura']=datostiempo['temperatura']
df['tempmax']=datostiempo['tempmax']
df['tempmin']=datostiempo['tempmin']
df['prob_precipitacion']=datostiempo['prob_precipitacion']
df['viento']=datostiempo['viento']
df['intensidad']=datostrafic['intensidad']
df['vmed']=datostrafic['vmed']
df.head()

,anio,mes,dia,SO2,CO,NO2,PM2.5,PM10,BEN,O3,...,calidadco,calidado3,calidad,temperatura,tempmax,tempmin,prob_precipitacion,viento,intensidad,vmed
0,16,1,1,7.50,0.30,35.125,13.000000,15.6,0.750,23.8,...,buena,buena,buena,10.9,14,7.6,0.00,8.0,890.573791,68.675248
1,16,1,2,7.25,0.28,27.375,5.000000,10.0,0.575,43.0,...,buena,buena,buena,8.4,12,5.0,3.81,16.5,-1.000000,-1.000000
2,16,1,3,6.75,0.28,27.750,5.000000,8.8,0.625,33.2,...,buena,buena,buena,7.4,10,4.0,0.00,19.3,-1.000000,-1.000000
3,16,1,4,6.75,0.22,19.750,3.333333,4.4,0.300,35.6,...,buena,buena,buena,12.1,13,8.0,0.51,38.7,-1.000000,-1.000000
4,16,1,5,6.75,0.28,27.125,3.000000,4.8,0.500,56.2,...,buena,buena,buena,6.9,9,5.0,4.32,23.5,-1.000000,-1.000000

In [18]:
df.to_csv("year2016respuesta.csv",index=False)